"""add book column

Revision ID: 0c799b9f9b69
Revises: 384a8cc388d2
Create Date: 2025-01-17 10:03:54.285283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c799b9f9b69'
down_revision = '384a8cc388d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('book', sa.Column('author', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'author')
    op.drop_column('book', 'title')
    # ### end Alembic commands ###
