"""add rental foreignkey

Revision ID: 384a8cc388d2
Revises: 77b687b17aa2
Create Date: 2025-01-16 13:06:18.926118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '384a8cc388d2'
down_revision = '77b687b17aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rental', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('rental', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'rental', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'rental', 'book', ['book_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.alter_column('rental', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('rental', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
